"use client";

import { useEffect, useState } from "react";

type Banner = { id: number; title: string; subtitle: string; imageUrl: string; mobileImageUrl?: string; linkUrl: string; placement: string; isActive: boolean; sortOrder: number };
const placementOptions = [{ value: "home_hero", label: "صفحه اصلی؛ زیر اسلایدشو" }, { value: "home_after_categories", label: "صفحه اصلی؛ بعد از دسته‌بندی‌ها" }, { value: "home_before_footer", label: "صفحه اصلی؛ قبل از فوتر" }, { value: "shop_top", label: "بالای صفحه فروشگاه" }, { value: "category_top", label: "بالای صفحات دسته‌بندی" }, { value: "product_top", label: "بالای صفحه محصول" }];
const empty = { title: "", subtitle: "", imageUrl: "", mobileImageUrl: "", linkUrl: "", placement: "home_after_categories", isActive: true, sortOrder: 0 };

export default function AdminBannersPage() {
  const [banners, setBanners] = useState<Banner[]>([]);
  const [form, setForm] = useState(empty);
  const [editing, setEditing] = useState<number | null>(null);
  const [message, setMessage] = useState("");
  const load = () => fetch("/api/admin/banners", { cache: "no-store" }).then((r) => r.json()).then((data) => setBanners(data.banners || [])).catch(() => setMessage("دریافت بنرها انجام نشد."));
  useEffect(() => { void load(); }, []);
  const change = (key: keyof typeof empty, value: string | boolean | number) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setMessage(""); const response = await fetch(editing ? `/api/admin/banners/${editing}` : "/api/admin/banners", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json().catch(() => ({})); if (!response.ok || !data.success) { setMessage(data.error || "ذخیره بنر انجام نشد."); return; } setMessage("بنر با موفقیت ذخیره شد."); setForm(empty); setEditing(null); await load(); };
  const edit = (banner: Banner) => { setEditing(banner.id); setForm({ title: banner.title, subtitle: banner.subtitle || "", imageUrl: banner.imageUrl, mobileImageUrl: banner.mobileImageUrl || "", linkUrl: banner.linkUrl || "", placement: banner.placement, isActive: banner.isActive, sortOrder: banner.sortOrder }); };
  const remove = async (id: number) => { if (!confirm("این بنر حذف شود؟")) return; await fetch(`/api/admin/banners/${id}`, { method: "DELETE" }); await load(); };
  return <div dir="rtl" className="max-w-6xl space-y-6"><div><h1 className="text-2xl font-black text-stone-900">مدیریت بنرهای سایت</h1><p className="mt-1 text-xs leading-6 text-stone-500">بنر را یک‌بار ثبت کنید و محل نمایش آن را انتخاب کنید. تصویر باید یک URL عمومی یا آدرس فایل آپلودشده باشد.</p></div>
    <form onSubmit={save} className="rounded-3xl border border-violet-200 bg-violet-50 p-5"><h2 className="text-sm font-black text-violet-950">{editing ? "ویرایش بنر" : "افزودن بنر جدید"}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">عنوان بنر<p className="font-normal text-stone-500">برای دسترسی‌پذیری و تشخیص در مدیریت</p><input required value={form.title} onChange={(e) => change("title", e.target.value)} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-xs font-bold">محل نمایش<select value={form.placement} onChange={(e) => change("placement", e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-2.5">{placementOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="text-xs font-bold sm:col-span-2">آدرس تصویر اصلی<p className="font-normal text-stone-500">مثال: https://... یا /images/banners/summer.webp</p><input required type="url" value={form.imageUrl} onChange={(e) => change("imageUrl", e.target.value)} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-xs font-bold">آدرس تصویر موبایل (اختیاری)<input type="url" value={form.mobileImageUrl} onChange={(e) => change("mobileImageUrl", e.target.value)} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-xs font-bold">لینک کلیک بنر (اختیاری)<p className="font-normal text-stone-500">مثال: /shop یا /product/slug</p><input value={form.linkUrl} onChange={(e) => change("linkUrl", e.target.value)} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-xs font-bold">ترتیب نمایش<input type="number" value={form.sortOrder} onChange={(e) => change("sortOrder", Number(e.target.value))} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={form.isActive} onChange={(e) => change("isActive", e.target.checked)} className="size-4" /> بنر فعال و قابل نمایش باشد</label></div><div className="mt-4 flex gap-2"><button className="rounded-xl bg-violet-700 px-5 py-3 text-xs font-black text-white">ذخیره بنر</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(empty); }} className="rounded-xl bg-white px-5 py-3 text-xs font-bold">انصراف از ویرایش</button>}</div>{message && <p className="mt-3 text-xs font-bold text-violet-900">{message}</p>}</form>
    <div className="space-y-3">{banners.map((banner) => <article key={banner.id} className="flex flex-col gap-4 rounded-3xl border bg-white p-4 shadow-sm sm:flex-row"><img src={banner.imageUrl} alt={banner.title} className="h-28 w-full rounded-2xl object-cover sm:w-56" /><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{banner.title}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${banner.isActive ? "bg-emerald-100 text-emerald-700" : "bg-stone-100 text-stone-500"}`}>{banner.isActive ? "فعال" : "غیرفعال"}</span></div><p className="mt-2 text-xs text-stone-500">{placementOptions.find((option) => option.value === banner.placement)?.label || banner.placement}</p><div className="mt-3 flex gap-2"><button onClick={() => edit(banner)} className="rounded-lg bg-stone-100 px-3 py-2 text-xs font-bold">ویرایش</button><button onClick={() => void remove(banner.id)} className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">حذف</button></div></div></article>)}</div>
  </div>;
}
